/**
 * @description This P360 Project Service class is part of the Public 360 integration
 * and is used as a service class for all related to projects in Public 360.
 *
 * @author Kenneth Soerensen (kenneth.sorensen@nav.com), NAV
 * @since 0.1.0, November 2024
 * @group Public 360 Integration
 * @see [Public 360 SIF API Documentation](https://help.360online.com/ReleaseInformation/SIF%20APIs%20-%20Documentation.pdf)
 * @example
 *
 */
public with sharing class P360ProjectService {
    public P360ProjectService() {
    }

    public void createProject() {
        // Implementation here
    }

    public void updateProject() {
        // Implementation here
    }

    public void getProject() {
        // Implementation here
    }
}
