name: "[PUSH] Quickbuild"
on:
  push:
    branches-ignore:
      - main
concurrency:
  group: ci-${{ github.ref_name }}
jobs:
  staticCodeValidation:
    name: Validation jobs
    uses: navikt/sf-shared/.github/workflows/ciStaticCodeValidation.yml@main
    permissions:
      contents: read
      security-events: write

  checkChanges:
    name: Check changes
    needs: staticCodeValidation
    runs-on: ubuntu-latest
    outputs:
      hasSrcChanges: ${{ steps.checkChanges.outputs.hasSrcChanges }}
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: navikt/sf-shared/.github/actions/checkForPackageChanges@ac5a20f2360145d954d3e412a02bcf7f06e15035
        id: checkChanges

  quickBuild:
    name: Quickbuild
    needs: checkChanges
    if: ${{ github.event_name == 'workflow_dispatch' || needs.checkChanges.outputs.hasSrcChanges == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:${{ vars.SFP_CONTAINER_VERSION }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Authenticate DevHub
        uses: navikt/sf-shared/.github/actions/authenticateOrg@ac5a20f2360145d954d3e412a02bcf7f06e15035
        with:
          auth-url: ${{ secrets.SF_DEVHUB_URL }}
          alias: "devhub"
          setDefaultDevhubUsername: "true"

      - name: "Quickbuild package"
        id: quickbuildPackage
        shell: bash
        run: |
          sfp quickbuild --devhubalias devhub --diffcheck --buildnumber ${GITHUB_RUN_ID} --branch ${GITHUB_REF#refs/heads/} --loglevel ${SFP_LOG_LEVEL}
        env:
          SFP_LOG_LEVEL: ${{ vars.SFP_LOG_LEVEL }}

      - name: Upload artifacts and logs
        if: always()
        uses: navikt/sf-shared/.github/actions/uploadWorkflowArtifactsAndLogs@ac5a20f2360145d954d3e412a02bcf7f06e15035
        with:
          artifactName: "build-artifacts"
          uploadArtifacts: true
          logName: "build-logs"
          publishLogs: true
