name: Relase to Production
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: false
        default: ""
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
jobs:
  release:
    uses: navikt/sf-shared/.github/workflows/release.yml@main
    with:
      release_tag: ${{ github.event.inputs.release_tag }}
    secrets:
      SF_DEVHUB_URL: ${{ secrets.SF_DEVHUB_URL }}
      TARGET_ORG_URL: ${{ secrets.SF_DEVHUB_URL }}
    permissions:
      contents: read
      packages: read
