name: "Run static code validation"
on:
  workflow_dispatch:
    inputs:
      validateEntireRepo:
        description: "Validate entire repo (unchecking will only validate the diff against main)"
        default: true
        required: false
        type: boolean
jobs:
  validate:
    uses: navikt/sf-platform/.github/workflows/ciStaticCodeValidation.yml@main
    with:
      validateEntireRepo: ${{ inputs.validateEntireRepo }}
    secrets:
      SF_DEVHUB_URL: ${{ secrets.SF_DEVHUB_URL  }}
    permissions:
      contents: read
